-- Hunter Harwood

-- Question 1
SELECT USERID
FROM UserBase
WHERE USERID NOT IN (
    SELECT USERID
    FROM Orders
);

-- Question 2
SELECT PRODUCTCODE
FROM ProductList
WHERE PRODUCTCODE NOT IN (
    SELECT PRODUCTCODE
    FROM Reviews
);

-- Question 3
SELECT USERID,
       FIRSTNAME,
       LASTNAME,
       USERNAME,
       PASSWORD,
       EMAIL,
       BIRTHDAY,
       WALLETFUNDS,
       CASE 
           WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, BIRTHDAY)/12) >= 18 THEN 'Adult'
           ELSE 'Minor'
       END AS AgeStatus
FROM USERBASE;


--  Question 4
SELECT PRODUCTCODE,
       PRODUCTNAME,
       DESCRIPTION,
       PRICE,
       PUBLISHER,
       GENRE,
       RELEASEDATE,
       CASE
           WHEN PRICE <= 20 THEN 'On Sale'
           ELSE 'Base Price'
       END AS PriceStatus
FROM PRODUCTLIST;


-- Question 5
SELECT USERID
FROM UserLibrary
WHERE PRODUCTCODE = 'GAME6'
  AND USERID IN (101, 102, 103);


-- Question 6
SELECT DISTINCT w.PRODUCTCODE
FROM WISHLIST w
JOIN REVIEWS r
    ON w.PRODUCTCODE = r.PRODUCTCODE
WHERE w.POSITION IN (1, 2)
  AND r.RATING >= 3;

-- Question 7
SELECT USERNAME,
       BIRTHDAY
FROM USERBASE
WHERE BIRTHDAY IN (
    SELECT BIRTHDAY
    FROM USERBASE
    GROUP BY BIRTHDAY
    HAVING COUNT(*) > 1
)
ORDER BY BIRTHDAY, USERNAME;

-- Question 8
SELECT *
FROM USERLIBRARY ul
CROSS JOIN WISHLIST w;

-- Question 9
SELECT USERID,
       USERNAME,
       EMAIL,
       NULL AS PRODUCTCODE,
       NULL AS PRODUCTNAME,
       NULL AS PRICE
FROM USERBASE
UNION ALL
SELECT NULL AS USERID,
       NULL AS USERNAME,
       NULL AS EMAIL,
       PRODUCTCODE,
       PRODUCTNAME,
       PRICE
FROM PRODUCTLIST;

-- Question 10
SELECT SENDERID AS USERID,
       CONTENT AS ACTIVITY,
       DATESENT AS ACTIVITY_DATE
FROM CHATLOG
UNION ALL
SELECT USERID,
       'Profile Update' AS ACTIVITY,
       NULL AS ACTIVITY_DATE
FROM USERPROFILE;

--Question 11
SELECT USERNAME
FROM USERBASE
WHERE USERID NOT IN (
    SELECT USERID
    FROM INFRACTIONS
);

-- Question 12
SELECT TITLE,
       DESCRIPTION
FROM COMMUNITYRULES
WHERE RULENUM NOT IN (
    SELECT RULENUM
    FROM INFRACTIONS
);

-- Question 13
SELECT u.USERNAME,
       u.EMAIL
FROM USERBASE u
JOIN INFRACTIONS i
    ON u.USERID = i.USERID
WHERE i.PENALTY IS NOT NULL;

-- Question 14
SELECT DISTINCT i.DATEASSIGNED AS ActivityDate
FROM INFRACTIONS i
JOIN USERBASE u
    ON i.USERID = u.USERID
JOIN USERSUPPORT s
    ON u.EMAIL = s.EMAIL
   AND TRUNC(i.DATEASSIGNED) = TRUNC(s.DATESUBMITTED)
ORDER BY ActivityDate;

-- Question 15
SELECT c.TITLE,
       i.PENALTY
FROM COMMUNITYRULES c
LEFT JOIN INFRACTIONS i
    ON c.RULENUM = i.RULENUM;

-- Question 16
SELECT *
FROM COMMUNITYRULES;

-- Question 17
SELECT TICKETID,
       EMAIL,
       ISSUE,
       DATESUBMITTED,
       DATEUPDATED,
       STATUS,
       CASE
           WHEN STATUS <> 'Closed' 
                AND DATEUPDATED <= SYSDATE - 7 THEN 'High Priority'
           ELSE 'Normal'
       END AS PriorityStatus
FROM USERSUPPORT;

-- Question 18
SELECT *
FROM USERSUPPORT s
CROSS JOIN INFRACTIONS i;

-- Question 19
SELECT TICKETID,
       DATEUPDATED
FROM USERSUPPORT
WHERE STATUS = 'Closed'
  AND TRUNC(DATEUPDATED) = TRUNC(DATEUPDATED);

-- Question 20
SELECT USERID,
       FIRSTNAME,
       LASTNAME,
       USERNAME,
       PASSWORD,
       EMAIL,
       BIRTHDAY,
       WALLETFUNDS,
       NULL AS INFRACTIONID,
       NULL AS RULENUM,
       NULL AS DATEASSIGNED,
       NULL AS PENALTY
FROM USERBASE
UNION ALL
SELECT USERID,
       NULL AS FIRSTNAME,
       NULL AS LASTNAME,
       NULL AS USERNAME,
       NULL AS PASSWORD,
       NULL AS EMAIL,
       NULL AS BIRTHDAY,
       NULL AS WALLETFUNDS,
       INFRACTIONID,
       RULENUM,
       DATEASSIGNED,
       PENALTY
FROM INFRACTIONS;

